### ISSUE TITLE
 Code for attention score visualization

### ISSUE THREAD

**Issue by zhaoxiongjun** [likith012/IMLE-Net#1]
Hello, will the code for attention score visualization be made public? I didn't find it in the code, thanks

**Comment by likith012** [comment]
Hi, I just noticed your issue. I have plans to make the rest of the code public. I will try to do that by this month's end.

**Comment by zhaoxiongjun** [comment]
Great!!!, Thanks

**Comment by Srijan221** [comment]
It's done now, the visualisation code is working great! This issue can be closed.
